### ISSUE TITLE
Installation Test Error

### ISSUE THREAD

**Issue by ksasi** [facebookresearch/PhysicsVAE#3]
Hi,

After performing the setup as per README, it appears the installation test is failing with error as below : 

ip_head: None
redis_password: None
>> Trying to initialize Ray as CLIENT...
num_cpus: 1
num_gpus: 0
redis_password: None
>> Ray was initialized as CLIENT
pybullet build time: Feb 14 2023 08:13:33
2023-02-14 09:49:54,120	INFO ppo.py:249 -- In multi-agent mode, policies will be optimized sequentially by the multi-GPU optimizer. Consider setting simple_optimizer=True if this doesn't work for you.
2023-02-14 09:49:54,120	INFO trainer.py:779 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
(RolloutWorker pid=31943) pybullet build time: Feb 14 2023 08:13:33
Traceback (most recent call last):
  File "/content/PhysicsVAE/rllib_driver.py", line 259, in <module>
    renderer = env_module.EnvRenderer(
  File "/content/PhysicsVAE/envs/rllib_env_imitation.py", line 276, in __init__
    super().__init__(**kwargs)
  File "/content/PhysicsVAE/env_renderer.py", line 37, in __init__
    super().__init__(title, cam, size, bgcolor)
TypeError: __init__() takes from 1 to 4 positional arguments but 5 were given
Exception ignored in: <function BulletClient.__del__ at 0x7f39d013da60>
Traceback (most recent call last):
  File "/content/PhysicsVAE/bullet/bullet_client.py", line 43, in __del__
AttributeError: 'NoneType' object has no attribute 'error'

Please note the setup is being done in Colab environment.

Thanks and Regards,
Sasikanth

**Comment by mytho-graphos** [comment]
Hello,have you resolve it?I got the same issue as this.When I try to run the installation test, I got this:

`2023-03-26 16:51:57,634 WARNING util.py:55 -- Install gputil for GPU system monitoring.
Traceback (most recent call last):
  File "rllib_driver.py", line 259, in <module>
    renderer = env_module.EnvRenderer(
  File "/root/PhysicsVAE/envs/rllib_env_imitation.py", line 276, in __init__
    super().__init__(**kwargs)
  File "/root/PhysicsVAE/env_renderer.py", line 37, in __init__
    super().__init__(title, cam, size, bgcolor)
TypeError: __init__() takes from 1 to 4 positional arguments but 5 were given`

I am working on it and still don't have a solving.I will be very appreciate if there is anything can help me.
